//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF___miniproject
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Table_1
    {
        public int id { get; set; }
        public string city_name { get; set; }
        public string city_id { get; set; }
        public Nullable<double> temperature { get; set; }
    }
}
